### ISSUE TITLE
[Bug] Unable to sign transactions on QR hardware wallet 

### ISSUE THREAD

**Issue by vivek-consensys** [MetaMask/metamask-mobile#13708]
Build: 7.41.0 (1583)
Android 13

1. Install MM
2. Recover from SRP
3. Add hardware wallet (QR - Keystone)
4. Import QR accounts from device
5. Visit Test dapp
6. Connect QR account
7. Sign permit / Sign typed data v4 

Expected: Sign transactions to be working, 'QR hardware' Label displayed on sign txn popup, alignment on popup.
Actual: Sign transactions does not work, QR code remains on display on Mobile after scanning QR code to sign with device. 'QR hardware' Label missing on sign txn popup . Misaligned on sign txn popup. 

Issue on 7.41.0:- 
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdBQ1E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04cfbe418f5ad08eb121519e8aa8e6fed4870bb8/Bug-QRSign-7.41.0.mp4)

Working on 7.40.0:- 
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTBBQ1E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df6666c265084051271935a23c3975d197d2272b/Bug-QRSign-7.40.0.mp4)

**Comment by dawnseeker8** [comment]
After the investigation and confirm the root cause is in QRInfo.tsx created from @MetaMask/confirmations 
The error was caused by submitQRSignature didnt provide the bind() function to KeyringController, which make the this scope in KeyringController change. which cause this.getOrAddQRKeyring is not a function error.
