### PR TITLE
fix(ios): patch fmt consteval build error on Xcode 26.4+

### PR DESCRIPTION
**Pull request by abretonc7s**
## **Description**

Xcode 26.4 (Apple Clang 21) introduces stricter `consteval` enforcement that breaks the `fmt` library (v11.0.2) bundled via `RCT-Folly`, causing 5 compilation errors in `format-inl.h`.

This patches `fmt/base.h` in the Podfile `post_install` block to disable `consteval` for all Apple Clang versions, falling back to `constexpr`. Same approach as the existing Folly coroutines patch. Safe for older Xcode versions — `constexpr` is the default fallback `fmt` already uses on many platforms. Survives `yarn setup` / `pod install` since the patch is re-applied each time.

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: N/A — build breakage on Xcode 26.4+

## **Manual testing steps**

```gherkin
Feature: iOS build with Xcode 26.4

  Scenario: developer builds iOS app
    Given Xcode 26.4 with Apple Clang 21 is installed

    When developer runs yarn start:ios
    Then the build completes without fmt consteval errors
```

### **Before**

Build fails with 5 `consteval` errors in `ios/Pods/fmt/include/fmt/format-inl.h`

### **After**

Build succeeds

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I've included tests if applicable
- [ ] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Adds a CocoaPods `post_install` patch that rewrites a vendored `fmt` header, which could affect formatting code generation or conflict with future `fmt` updates, but is limited in scope to a single preprocessor toggle during install.
> 
> **Overview**
> Prevents Xcode 26.4+ build failures by extending the `Podfile` `post_install` step to patch `fmt/include/fmt/base.h`, forcing `FMT_USE_CONSTEVAL` from `1` to `0` (with a regex tolerant of whitespace/indentation) and handling file permissions similarly to the existing Folly patch.
> 
> Updates `Podfile.lock` with the new `PODFILE CHECKSUM` reflecting the `Podfile` change.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 2c4aba0ae5db2a649f94dde1e2cd54481fc5f79e. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: ios/Podfile [hunk 1]
```diff
@@ -165,6 +165,27 @@ post_install do |installer|
...
+  # The fmt library's consteval detection doesn't account for broken consteval
+  # in newer Apple Clang versions. Patch base.h to force consteval off.
+  Dir.glob(installer.sandbox.root + "fmt/include/fmt/base.h") do |file|
+    begin
+      system "chmod +w #{file}"
+      contents = File.read(file)
+      modified = contents.gsub(
+        /defined\(__apple_build_version__\) && __apple_build_version__ < 14000029L/,
+        'defined(__apple_build_version__)'
+      )
```
[the remark this answers is not in the document]
Comment (abretonc7s) [reply ios/Podfile]: Fixed in 36dc5cb. Replaced fragile regex with direct `#define FMT_USE_CONSTEVAL 1` → `0` replacement using whitespace-tolerant regex `/#\s*define FMT_USE_CONSTEVAL 1/`.

File: ios/Podfile [hunk 2]
```diff
@@ -165,6 +165,19 @@ post_install do |installer|
...
+  # in newer Apple Clang versions. Patch base.h to force consteval off.
+  Dir.glob(installer.sandbox.root + "fmt/include/fmt/base.h") do |file|
+    system "chmod +w #{file}"
+    contents = File.read(file)
+    modified = contents.gsub(
+      /defined\(__apple_build_version__\) && __apple_build_version__ < 14000029L/,
+      'defined(__apple_build_version__)'
+    )
+    File.write(file, modified)
+  end
```
[the remark this answers is not in the document]
Comment (abretonc7s) [reply ios/Podfile:182]: Not applicable — begin/rescue, chmod +w, File.writable? fallback, and chmod -w restoration were already present when this comment was posted.

File: ios/Podfile [hunk 3]
```diff
@@ -165,6 +165,24 @@ post_install do |installer|
...
   end
 
+  # Fix fmt compilation error with Xcode 26 / Clang 21 consteval strictness
+  # Directly disable FMT_USE_CONSTEVAL rather than patching the detection logic,
+  # which varies across fmt versions and is fragile to match with a regex.
+  Dir.glob(installer.sandbox.root + "fmt/include/fmt/base.h") do |file|
+    begin
+      system "chmod +w #{file}"
+      contents = File.read(file)
+      modified = contents.gsub('#define FMT_USE_CONSTEVAL 1', '#define FMT_USE_CONSTEVAL 0')
```
[the remark this answers is not in the document]
Comment (abretonc7s) [reply ios/Podfile]: Fixed in 36dc5cb. Switched to `/#\s*define FMT_USE_CONSTEVAL 1/` regex which handles the indented `#  define` in fmt v11.0.2. Verified against local Pods copy — matches and replaces both instances.

**Review by michalconsensys — DISMISSED** [review]

**Comment by gambinish** [comment]
This seems like something that should have flagged mobile platform team 🤔

**Review by Cal-L — DISMISSED** [review]
LGTM

**Review by Cal-L — APPROVED** [review]
LGTM
