### PR TITLE
fix: cp-7.41.0 13708 fix the submitQRSignature scope issue

### LINKED ISSUE #13708: [Bug] Unable to sign transactions on QR hardware wallet
Build: 7.41.0 (1583)
Android 13

1. Install MM
2. Recover from SRP
3. Add hardware wallet (QR - Keystone)
4. Import QR accounts from device
5. Visit Test dapp
6. Connect QR account
7. Sign permit / Sign typed data v4 

Expected: Sign transactions to be working, 'QR hardware' Label displayed on sign txn popup, alignment on popup.
Actual: Sign transactions does not work, QR code remains on display on Mobile after scanning QR code to sign with device. 'QR hardware' Label missing on sign txn popup . Misaligned on sign txn popup. 

Issue on 7.41.0:- 
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdBQ1E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04cfbe418f5ad08eb121519e8aa8e6fed4870bb8/Bug-QRSign-7.41.0.mp4)

Working on 7.40.0:- 
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTBBQ1E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df6666c265084051271935a23c3975d197d2272b/Bug-QRSign-7.40.0.mp4)

### PR DESCRIPTION
**Pull request by dawnseeker8**
## **Description**
This QR is to fix the bug report #13708 , 
The affect area was Personal sign, Sign Typed data v4, sign permit feature.
The error was caused by `submitQRSignature` didnt provide the bind() function to KeyringController, which make the `this` scope in KeyringController change. which cause `this.getOrAddQRKeyring is not a function` error.

## **Related issues**

Fixes: #13708 

## **Manual testing steps**

1.Install MM
2. Recover from SRP
3. Add hardware wallet (QR - Keystone)
4. Import QR accounts from device
5. Visit Test dapp
6. Connect QR account
7. Sign permit / Sign typed data v4

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by vivek-consensys** [comment]
Tested on iOS using [Bitrise Build ](https://app.bitrise.io/build/52abbb72-b32c-48c6-a2c9-4254b351c8fc?tab=artifacts).

**Review by MarioAslau — APPROVED** [review]

**Review by jpuri — APPROVED** [review]

**Review by sleepytanya — APPROVED** [review]
